### ISSUE TITLE
Issue with feh loading images

### ISSUE THREAD

**Issue by Dielerorn** [ganifladi/blurme#3]
Upon executing the script, I get a long, never ending series of errors from feh saying it cannot load the images in /home/user/.cache/blurme/

Here are the errors:
`feh WARNING: /home/austin/.cache/blurme/trans-0 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-1 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-2 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-3 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-4 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-5 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-6 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-7 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-8 does not exist - skipping
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh WARNING: /home/austin/.cache/blurme/trans-9 does not exist - skipping`

**Comment by prkrkmr** [comment]
`tail -n1 ~/.fehbg | cut -d "'" -f6  `

If the output for above command is blank then you will need to change f6 to f2 in the script so that it can get the filename of the background. The change should look like this. 

`tail -n1 ~/.fehbg | cut -d "'" -f2  `

**Comment by saivarshith2000** [comment]
I tried `tail -n1 ~/.fehbg | cut -d "'" -f6`. The output was `feh --bg-scale`. The problem still persists

**Comment by hthaneunt** [comment]
try installing package [bc](https://www.archlinux.org/packages/extra/x86_64/bc/)

**Comment by ecesar88** [comment]
I tried tail -n1 ~/.fehbg | cut -d "'" -f6, the output was blank. Then i ran tail -n1 ~/.fehbg | cut -d "'" -f2, but the problem still persists. I already have bc installed. Don't know what could cause this problem.

**Comment by Dielerorn** [comment]
Changing `tail -n1 ~/.fehbg | cut -d "'" -f6` to `tail -n1 ~/.fehbg | cut -d "'" -f2` seems to make it almost work properly.

Now I'm getting:
`
cp: missing destination file operand after '/home/austin/.local/share/blurme/copied-bg
Try cp --help for more information.
convert: no images defined /tmp/blurme-trans-0.tmp @ error/convert.c/ConvertImageCommand/3288.
rm: cannot remove '/tmp/blurme-trans-0.tmp': No such file or directory
^Cfeh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
feh: No loadable images specified.
See 'feh --help' or 'man feh' for detailed usage information
`

During that error message, the background constantly fades back and forth between blurred and unblurred regardless of whether or not a window is present.

**Comment by Dielerorn** [comment]
The answer here actually fixed it: https://github.com/ganifladi/blurme/issues/9
Closing this issue now
