### ISSUE TITLE
How to fix script not finding current wallpaper

### ISSUE THREAD

**Issue by felipecustodio** [ganifladi/blurme#7]
I believe feh output has changed, so changing the lines that contain

**tail -n1 ~/.fehbg | cut -d "'" -f6**

to

**tail -n1 ~/.fehbg | cut -d "'" -f2**

solved the problem for me :)

**Comment by 8r2y5** [comment]
I added pr with that change #8

**Comment by ganifladi** [comment]
Merged with 8r2y5s PR and should be working now :)
Thanks for contributing!
