### ISSUE TITLE
Blur loop 

### ISSUE THREAD

**Issue by ghost** [ganifladi/blurme#9]
Hello I have i3 on Arch, when I execute the script it start bluring the wallpaper but when it's finished it don't stay like this. The output of -v look like this

BLURME: Blur wallpaper ...
BLURME: 10%
BLURME: 20%
BLURME: 30%
BLURME: 40%
BLURME: 50%
BLURME: 60%
BLURME: 70%
BLURME: 80%
BLURME: 90%
BLURME: 100%
BLURME: Done!
BLURME: Blur wallpaper ...
BLURME: 10%
BLURME: 20%
BLURME: 30%
BLURME: 40%
BLURME: 50%
BLURME: 60%
BLURME: 70%
BLURME: 80%
BLURME: 90%
BLURME: 100%
BLURME: Done!

and it keep doing that forever.

**Comment by khazelrigg** [comment]
I was also having this issue and it seems to be coming from the cut command not being used correctly. Anywhere in the script you see `cut -d "'" -f6` replace it with `cut -d "'" -f2` 
Check this pull request #8

**Comment by ganifladi** [comment]
Should be solved now by merging with PR [#8](https://github.com/ganifladi/blurme/pull/8)
